---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
type: Opaque
stringData:
  credentials: |
    {
      "client_id": "xxxxxx",
      "client_secret": "xxxxxx",
      "url": "https://keycloak.example.com",
      "base_path": "/auth",
      "realm": "master"
    }  
