---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: keycloak-provider
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  # currently stored here:  https://gitlab.com/corewire/images/provider-keycloak/container_registry/4538877
  package: registry.gitlab.com/corewire/images/provider-keycloak:v0.0.0-14.gb43e0c4
