# Example 1: Basic Realm Configuration
# This example demonstrates the minimum required fields to create a realm.
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: basic-realm  # The name of the realm in Kubernetes
spec:
  forProvider:
    realm: "basic-realm"  # The name of the realm in Keycloak
  providerConfigRef:
    name: "keycloak-provider-config"  # Reference to the ProviderConfig resource

---
# Example 2: Realm with Advanced Settings
# This example includes additional fields like 'enabled', 'displayName', and 'attributes'.
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: advanced-realm
spec:
  forProvider:
    realm: "advanced-realm"
    enabled: true  # Whether the realm is enabled or not
    displayName: "Advanced Realm"  # Display name for the realm
    attributes:
      customAttribute: "value"  # Additional attributes for the realm
  providerConfigRef:
    name: "keycloak-provider-config"

---
# Example 3: Realm with Security Policies
# This example demonstrates how to configure security policies like password policies and OTP.
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: secure-realm
spec:
  forProvider:
    realm: "secure-realm"
    passwordPolicy: "length(8) and digits(2)"  # Password policy
    otpPolicy:
      - algorithm: "HOTP"
        digits: 6
        type: "totp"
  providerConfigRef:
    name: "keycloak-provider-config"

---
# Example 4: Realm with SMTP Server Configuration
# This example shows how to configure an SMTP server for the realm.
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: smtp-realm
spec:
  forProvider:
    realm: "smtp-realm"
    smtpServer:
      - host: "smtp.example.com"
        port: "587"
        from: "noreply@example.com"
  providerConfigRef:
    name: "keycloak-provider-config"

