---
# Example 1: Basic User
# This is a basic user with the minimum required fields.
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: bree
spec:
  forProvider:
    realmId: "dev"  # The realm to which this user belongs
    username: "bree"     # The username for this user
  providerConfigRef:
    name: "keycloak-provider-config"  # Reference to the provider configuration